### ISSUE TITLE
cURL error 6: Could not resolve host: Address

### ISSUE THREAD

**Issue by vplaton** [daaner/NovaPoshta#27]
Приветствую!
Пытаюсь использовать данный пакет, но из коробки выдает ошибку при получении через поиск списка населенных пунктов Украины. Использую на локалке OSPanel

```
$adr = new Address;
$adr->setLimit(20);
$settlements = $adr->getSettlements('бров');
dd($settlements);

Illuminate\Http\Client\ConnectionException
cURL error 6: Could not resolve host: Address (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) 
```

Помогите разобраться в чем проблема!

**Comment by daaner** [comment]
У тебя в локальной пыхе все в норме? Покажи на какой адрес оно пытается отправить запрос

**Comment by daaner** [comment]
А еще бывает, что Новая Почта не работает и апи запросы не уходят)
