### ISSUE TITLE
Missing params

### ISSUE THREAD

**Issue by pdwebdev** [daaner/NovaPoshta#28]
1. В трейті SenderProperty - getSender з конфігу витягує неправильний CitySender.
2.  В моделі InternetDocument в save потрібно додати getWeight, це обов'язковий параметр.

**Comment by daaner** [comment]
1 поправил

**Comment by daaner** [comment]
а getWeight покрывается getSeatsAmount, это объемный вес. Я подумаю как проверить, если вы указываете вес, чтоб оно не выбирало объемный.

**Comment by daaner** [comment]
Хотя, такое уже есть, но нужно перепроверить

**Comment by daaner** [comment]
В общем, из-за выбора веса идет выборка объемного, так что все должно быть ок
